### ISSUE TITLE
Error starting autoraise with Homebrew

### ISSUE THREAD

**Issue by fgsch** [Dimentium/homebrew-autoraise#9]
```
$ brew services start dimentium/autoraise/autoraise
Error: undefined method `plist_startup' for #<Formula autoraise (stable) /opt/homebrew/Library/Taps/dimentium/homebrew-autoraise/autoraise.rb>
Did you mean?  plist_name
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:71:in `service_startup?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:280:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:122:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:130:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

And:

```
brew config
HOMEBREW_VERSION: 4.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff899e5b3ff6731208564ef502db237e2627e8ba
Last commit: 6 days ago
Core tap JSON: 24 Dec 10:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_MAKE_JOBS: 14
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 14-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

Same error mentioned here: https://stackoverflow.com/questions/77659527/mongodb-via-brew-services-undefined-method-plist-startup

It looks like you might need to update the formula.

**Comment by jmechnich** [comment]
@fgsch thanks for reporting this and Merry Christmas 😄

**Comment by fgsch** [comment]
Thank you for looking into this. Unfortunately there is another error when installing it now:

```
$ brew install autoraise
==> Fetching dimentium/autoraise/autoraise
==> Downloading https://github.com/sbmpost/AutoRaise/archive/refs/tags/
Already downloaded: /Users/xxxxx/Library/Caches/Homebrew/downloads/13b0df128f7d687963e17618b9c7218ea86ed0fde37f14cf15289e2676e4accf--AutoRaise-4.7.tar.gz
==> Installing autoraise from dimentium/autoraise
==> make clean
==> make
Error: Formula specified both service and plist
🍺  /opt/homebrew/Cellar/autoraise/4.7: 5 files, 141.4KB, built in 1 second
==> Running `brew cleanup autoraise`...```

**Comment by jmechnich** [comment]
Oh sorry...did not catch that without reinstalling the formula.

**Comment by jmechnich** [comment]
@fgsch this should be fixed now. Could you confirm that it works for you now?

**Comment by fgsch** [comment]
Thank you, it seems to be working as expected now!
